In [15]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
labeller = LabelEncoder()

In [6]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\synthetic_coffee_health_10000.csv")

In [8]:
df.head()

,ID,Age,Gender,Country,Coffee_Intake,Caffeine_mg,Sleep_Hours,Sleep_Quality,BMI,Heart_Rate,Stress_Level,Physical_Activity_Hours,Health_Issues,Occupation,Smoking,Alcohol_Consumption
0,1,40,Male,Germany,3.5,328.1,7.5,Good,24.9,78,Low,14.5,NaN,Other,0,0
1,2,33,Male,Germany,1.0,94.1,6.2,Good,20.0,67,Low,11.0,NaN,Service,0,0
2,3,42,Male,Brazil,5.3,503.7,5.9,Fair,22.7,59,Medium,11.2,Mild,Office,0,0
3,4,53,Male,Germany,2.6,249.2,7.3,Good,24.7,71,Low,6.6,Mild,Other,0,0
4,5,32,Female,Spain,3.1,298.0,5.3,Fair,24.1,76,Medium,8.5,Mild,Student,0,1

In [10]:
def tozalovchi(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [16]:
def encodla(df):
    for col in df.columns:
        if df[col].dtype == 'object':
            if df[col].nunique() <= 4:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=labeller.fit_transform(df[col])
    return df

In [12]:
df = tozalovchi(df)

In [17]:
df = encodla(df)

In [18]:
df

,ID,Age,Country,Coffee_Intake,Caffeine_mg,Sleep_Hours,BMI,Heart_Rate,Physical_Activity_Hours,Occupation,...,Sleep_Quality_Excellent,Sleep_Quality_Fair,Sleep_Quality_Good,Sleep_Quality_Poor,Stress_Level_High,Stress_Level_Low,Stress_Level_Medium,Health_Issues_Mild,Health_Issues_Moderate,Health_Issues_Severe
0,1,40,7,3.5,328.1,7.5,24.9,78,14.5,2,...,0,0,1,0,0,1,0,1,0,0
1,2,33,7,1.0,94.1,6.2,20.0,67,11.0,3,...,0,0,1,0,0,1,0,1,0,0
2,3,42,2,5.3,503.7,5.9,22.7,59,11.2,1,...,0,1,0,0,0,0,1,1,0,0
3,4,53,7,2.6,249.2,7.3,24.7,71,6.6,2,...,0,0,1,0,0,1,0,1,0,0
4,5,32,15,3.1,298.0,5.3,24.1,76,8.5,4,...,0,1,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,50,10,2.1,199.8,6.0,30.5,50,10.1,0,...,0,1,0,0,0,0,1,0,1,0
9996,9997,18,18,3.4,319.2,5.8,19.1,71,11.6,3,...,0,1,0,0,0,0,1,1,0,0
9997,9998,26,4,1.6,153.4,7.1,25.1,66,13.7,4,...,0,0,1,0,0,1,0,1,0,0
9998,9999,40,5,3.4,327.1,7.0,19.3,80,0.1,4,...,0,0,1,0,0,1,0,1,0,0
9999,10000,42,2,2.9,277.5,6.4,28.1,72,9.8,4,...,0,0,1,0,0,1,0,1,0,0