In [44]:
import pandas as pd
import numpy as np

# from joblib import dump
# import os

# import matplotlib.pyplot as plt
# import seaborn as sns
# import klib
import tabulate 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler,LabelEncoder

minmax = MinMaxScaler()
labeller = LabelEncoder()

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression

RF_Reg = RandomForestRegressor()
DT_Reg = DecisionTreeRegressor()
svc = SVR()
LR_reg = LinearRegression()

from sklearn.metrics import classification_report, accuracy_score

In [60]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\house_prices_dataset.csv")

In [35]:
df1 = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\house_prices_dataset.csv")

In [38]:
df.head()

   square_feet  num_rooms  age  distance_to_city(km)          price
0  2248.357077          3   92             22.997972  200374.090410
1  1930.867849          2   22             13.984254  268784.847337
2  2323.844269          6   33             21.500945  315020.857676
3  2761.514928          3   63             10.343638  355111.468459
4  1882.923313          7   54             25.485200  234197.123903

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   square_feet           10000 non-null  float64
 1   num_rooms             10000 non-null  int64
 2   age                   10000 non-null  int64
 3   distance_to_city(km)  10000 non-null  float64
 4   price                 10000 non-null  float64
dtypes: float64(3), int64(2)
memory usage: 390.8 KB

# df1 datasetga qoshimcha qurilgan yil qiymatini qoshish

In [40]:
qiymat = df1['age'].values
df1['BuiltYear'] = list(map(lambda x: 2025 - x, qiymat))

In [42]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   square_feet           10000 non-null  float64
 1   num_rooms             10000 non-null  int64
 2   age                   10000 non-null  int64
 3   distance_to_city(km)  10000 non-null  float64
 4   price                 10000 non-null  float64
 5   BuiltYear             10000 non-null  int64
dtypes: float64(3), int64(3)
memory usage: 468.9 KB

In [61]:
def scaller(data):
    for col in data.columns:
        if data[col].dtypes != 'object' and data[col].name != 'price':
            data[col] = minmax.fit_transform(data[[col]])

In [62]:
scaller(df)

In [64]:
df.head()

   square_feet  num_rooms       age  distance_to_city(km)          price
0     0.504850        0.2  0.929293              0.758709  200374.090410
1     0.413173        0.0  0.222222              0.447824  268784.847337
2     0.526648        0.8  0.333333              0.707076  315020.857676
3     0.653028        0.2  0.636364              0.322259  355111.468459
4     0.399329        1.0  0.545455              0.844494  234197.123903