In [70]:
import pandas as pd
import numpy as np

# from joblib import dump
# import os

# import matplotlib.pyplot as plt
# import seaborn as sns
# import klib
import tabulate 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler,LabelEncoder

minmax = MinMaxScaler()
labeller = LabelEncoder()

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression

RF_Reg = RandomForestRegressor()
DT_Reg = DecisionTreeRegressor()
svc = SVR()
LR_reg = LinearRegression()

from sklearn.metrics import r2_score, mean_absolute_error

In [60]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\house_prices_dataset.csv")

In [35]:
df1 = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\house_prices_dataset.csv")

In [38]:
df.head()

   square_feet  num_rooms  age  distance_to_city(km)          price
0  2248.357077          3   92             22.997972  200374.090410
1  1930.867849          2   22             13.984254  268784.847337
2  2323.844269          6   33             21.500945  315020.857676
3  2761.514928          3   63             10.343638  355111.468459
4  1882.923313          7   54             25.485200  234197.123903

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   square_feet           10000 non-null  float64
 1   num_rooms             10000 non-null  int64
 2   age                   10000 non-null  int64
 3   distance_to_city(km)  10000 non-null  float64
 4   price                 10000 non-null  float64
dtypes: float64(3), int64(2)
memory usage: 390.8 KB

# df1 datasetga qoshimcha qurilgan yil qiymatini qoshish

In [40]:
qiymat = df1['age'].values
df1['BuiltYear'] = list(map(lambda x: 2025 - x, qiymat))

In [42]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   square_feet           10000 non-null  float64
 1   num_rooms             10000 non-null  int64
 2   age                   10000 non-null  int64
 3   distance_to_city(km)  10000 non-null  float64
 4   price                 10000 non-null  float64
 5   BuiltYear             10000 non-null  int64
dtypes: float64(3), int64(3)
memory usage: 468.9 KB

In [61]:
def scaller(data):
    for col in data.columns:
        if data[col].dtypes != 'object' and data[col].name != 'price':
            data[col] = minmax.fit_transform(data[[col]])

In [62]:
scaller(df)

In [84]:
scaller(df1)

In [64]:
df.head()

   square_feet  num_rooms       age  distance_to_city(km)          price
0     0.504850        0.2  0.929293              0.758709  200374.090410
1     0.413173        0.0  0.222222              0.447824  268784.847337
2     0.526648        0.8  0.333333              0.707076  315020.857676
3     0.653028        0.2  0.636364              0.322259  355111.468459
4     0.399329        1.0  0.545455              0.844494  234197.123903

In [86]:
df1.head()

,square_feet,num_rooms,age,distance_to_city(km),price,BuiltYear
0,0.504850,0.2,0.929293,0.758709,200374.090410,0.070707
1,0.413173,0.0,0.222222,0.447824,268784.847337,0.777778
2,0.526648,0.8,0.333333,0.707076,315020.857676,0.666667
3,0.653028,0.2,0.636364,0.322259,355111.468459,0.363636
4,0.399329,1.0,0.545455,0.844494,234197.123903,0.454545

In [65]:
x = df.drop('price', axis=1)
y = df['price']

In [87]:
x = df1.drop('price', axis=1)
y = df1['price']

In [67]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2 ,random_state = 56)

In [88]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2 ,random_state = 56)

# Linear Regression

In [71]:
LR_reg.fit(x_train,y_train)

LinearRegression()

In [73]:
pred1 = LR_reg.predict(x_test)

print(r2_score(y_test,pred1))
print(mean_absolute_error(y_test,pred1))

0.9598315616245986
15908.806012189982

# Decision tree

In [74]:
DT_Reg.fit(x_train,y_train)

DecisionTreeRegressor()

In [76]:
pred2 = DT_Reg.predict(x_test)

print(r2_score(y_test,pred2))
print(mean_absolute_error(y_test,pred2))

0.8943225386529081
25748.15628022909

# Random forest

In [77]:
RF_Reg.fit(x_train,y_train)

RandomForestRegressor()

In [79]:
pred3 = RF_Reg.predict(x_test)

print(r2_score(y_test,pred3))
print(mean_absolute_error(y_test,pred3))

0.9476641531764418
18200.762585214343

# suport vector machine

In [81]:
svc.fit(x_train,y_train)

SVR()

In [83]:
pred4 = svc.predict(x_test)

print(r2_score(y_test,pred4))
print(mean_absolute_error(y_test,pred4))

0.00541778096230372
79607.40137221773

# With feature engeeniring

# linear regression

In [90]:
LR_reg.fit(x_train,y_train)

LinearRegression()

In [92]:
pred1 = LR_reg.predict(x_test)

print(r2_score(y_test,pred1))
print(mean_absolute_error(y_test,pred1))

0.9598315616245986
15908.806012189983

# Decision tree

In [95]:
DT_Reg.fit(x_train,y_train)

DecisionTreeRegressor()

In [97]:
pred2 = DT_Reg.predict(x_test)

print(r2_score(y_test,pred2))
print(mean_absolute_error(y_test,pred2))

0.894753413913754
25830.32637663111

# Random forest

In [98]:
RF_Reg.fit(x_train,y_train)

RandomForestRegressor()

In [100]:
pred3 = RF_Reg.predict(x_test)

print(r2_score(y_test,pred3))
print(mean_absolute_error(y_test,pred3))

0.9476938789143662
18161.99847492934

# suport vector machine

In [101]:
svc.fit(x_train,y_train)

SVR()

In [103]:
pred4 = svc.predict(x_test)

print(r2_score(y_test,pred4))
print(mean_absolute_error(y_test,pred4))

0.004839615188823365
79634.9443982144

# Tabulate

In [105]:
from tabulate import tabulate

In [110]:
headers = ['Model name', 'r2', 'mae', 'r2(Feature_Engineered)', 'mae(Feature_Engineered)']

data = [['Linear model', 0.9598, 15908, 0.9598,15908],
        ['Decision tree', 0.8943, 25748, 0.8947,25830],
        ['Random forest', 0.9476, 18200, 0.9476, 18161],
        ['Suport vector machine', 0.005, 79607, 0.0048,79634]]

info = tabulate(data,headers=headers, tablefmt='fancy_grid')

print(info)

╒═══════════════════════╤════════╤═══════╤══════════════════════════╤═══════════════════════════╕
│ Model name            │     r2 │   mae │   r2(Feature_Engineered) │   mae(Feature_Engineered) │
╞═══════════════════════╪════════╪═══════╪══════════════════════════╪═══════════════════════════╡
│ Linear model          │ 0.9598 │ 15908 │                   0.9598 │                     15908 │
├───────────────────────┼────────┼───────┼──────────────────────────┼───────────────────────────┤
│ Decision tree         │ 0.8943 │ 25748 │                   0.8947 │                     25830 │
├───────────────────────┼────────┼───────┼──────────────────────────┼───────────────────────────┤
│ Random forest         │ 0.9476 │ 18200 │                   0.9476 │                     18161 │
├───────────────────────┼────────┼───────┼──────────────────────────┼───────────────────────────┤
│ Suport vector machine │ 0.005  │ 79607 │                   0.0048 │                     79634 │
╘═══════════════════════╧════════╧═══════╧══════════════════════════╧═══════════════════════════╛