In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\possum.csv")

In [5]:
df.head()

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0
1,2,1,Vic,f,6.0,92.5,57.6,91.5,36.5,72.5,51.2,16.0,28.5,33.0
2,3,1,Vic,f,6.0,94.0,60.0,95.5,39.0,75.4,51.9,15.5,30.0,34.0
3,4,1,Vic,f,6.0,93.2,57.1,92.0,38.0,76.1,52.2,15.2,28.0,34.0
4,5,1,Vic,f,2.0,91.5,56.3,85.5,36.0,71.0,53.2,15.1,28.5,33.0

In [6]:
def toldiruvchi(df):
    for cols in df.columns:
        if df[cols].isnull().any():
            if df[cols].dtype == 'object':
                    df[cols].fillna(df[cols].mode()[0],inplace=True)
            else:
                df[cols].fillna(df[cols].mean(),inplace=True)
    return df

In [7]:
toldiruvchi(df)

C:\Users\bunyo\AppData\Local\Temp\ipykernel_2140\197827287.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[cols].fillna(df[cols].mean(),inplace=True)

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0
1,2,1,Vic,f,6.0,92.5,57.6,91.5,36.5,72.5,51.2,16.0,28.5,33.0
2,3,1,Vic,f,6.0,94.0,60.0,95.5,39.0,75.4,51.9,15.5,30.0,34.0
3,4,1,Vic,f,6.0,93.2,57.1,92.0,38.0,76.1,52.2,15.2,28.0,34.0
4,5,1,Vic,f,2.0,91.5,56.3,85.5,36.0,71.0,53.2,15.1,28.5,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,100,7,other,m,1.0,89.5,56.0,81.5,36.5,66.0,46.8,14.8,23.0,27.0
100,101,7,other,m,1.0,88.6,54.7,82.5,39.0,64.4,48.0,14.0,25.0,33.0
101,102,7,other,f,6.0,92.4,55.0,89.0,38.0,63.5,45.4,13.0,25.0,30.0
102,103,7,other,m,4.0,91.5,55.2,82.5,36.5,62.9,45.9,15.4,25.0,29.0
103,104,7,other,f,3.0,93.6,59.9,89.0,40.0,67.6,46.0,14.8,28.5,33.5

In [8]:
from sklearn.preprocessing import LabelEncoder
labeller = LabelEncoder()

In [9]:
def encodlovchi(df):
    for cols in df.columns:
        if df[cols].dtype=='object':
            if df[cols].nunique()<=5:
                dummies=pd.get_dummies(df[cols],prefix=cols, dtype=int)
                df=pd.concat([df.drop(columns=[cols]),dummies],axis=1)
            else:
                df[cols]=labeller.fit_transform(df[cols])
    return df

In [12]:
df = encodlovchi(df)

In [14]:
df.sample(5)

,case,site,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly,Pop_Vic,Pop_other,sex_f,sex_m
35,36,2,7.0,93.3,59.3,88.0,35.0,74.3,52.0,14.9,25.5,36.0,1,0,0,1
31,32,1,4.0,94.3,56.7,94.0,39.0,74.8,52.0,14.9,28.0,34.0,1,0,1,0
68,69,5,5.0,98.0,55.6,88.0,37.5,65.0,45.6,15.0,28.5,34.0,0,1,0,1
80,81,6,3.0,90.6,56.0,85.5,38.0,65.6,41.7,17.0,27.5,35.0,0,1,0,1
90,91,7,3.0,97.8,59.6,89.0,38.0,65.5,48.0,15.0,26.0,32.0,0,1,0,1

In [15]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

In [16]:
def scale_qiluvchi(df):
    num_col=df.select_dtypes(include=['int64','int32','float64']).columns.drop('hdlngth')
    df[num_col]=minmax.fit_transform(df[num_col])
    return df

In [17]:
scale_qiluvchi(df)

,case,site,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly,Pop_Vic,Pop_other,sex_f,sex_m
0,0.000000,0.0,0.875,94.1,0.559140,0.651163,0.363636,0.806818,0.893082,0.48,0.60,0.733333,1.0,0.0,0.0,1.0
1,0.009709,0.0,0.625,92.5,0.408602,0.767442,0.409091,0.693182,0.685535,0.64,0.65,0.533333,1.0,0.0,1.0,0.0
2,0.019417,0.0,0.625,94.0,0.537634,0.953488,0.636364,0.857955,0.729560,0.54,0.80,0.600000,1.0,0.0,1.0,0.0
3,0.029126,0.0,0.625,93.2,0.381720,0.790698,0.545455,0.897727,0.748428,0.48,0.60,0.600000,1.0,0.0,1.0,0.0
4,0.038835,0.0,0.125,91.5,0.338710,0.488372,0.363636,0.607955,0.811321,0.46,0.65,0.533333,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,0.961165,1.0,0.000,89.5,0.322581,0.302326,0.409091,0.323864,0.408805,0.40,0.10,0.133333,0.0,1.0,0.0,1.0
100,0.970874,1.0,0.000,88.6,0.252688,0.348837,0.636364,0.232955,0.484277,0.24,0.30,0.533333,0.0,1.0,0.0,1.0
101,0.980583,1.0,0.625,92.4,0.268817,0.651163,0.545455,0.181818,0.320755,0.04,0.30,0.333333,0.0,1.0,1.0,0.0
102,0.990291,1.0,0.375,91.5,0.279570,0.348837,0.409091,0.147727,0.352201,0.52,0.30,0.266667,0.0,1.0,0.0,1.0
103,1.000000,1.0,0.250,93.6,0.532258,0.651163,0.727273,0.414773,0.358491,0.40,0.65,0.566667,0.0,1.0,1.0,0.0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   case       104 non-null    float64
 1   site       104 non-null    float64
 2   age        104 non-null    float64
 3   hdlngth    104 non-null    float64
 4   skullw     104 non-null    float64
 5   totlngth   104 non-null    float64
 6   taill      104 non-null    float64
 7   footlgth   104 non-null    float64
 8   earconch   104 non-null    float64
 9   eye        104 non-null    float64
 10  chest      104 non-null    float64
 11  belly      104 non-null    float64
 12  Pop_Vic    104 non-null    float64
 13  Pop_other  104 non-null    float64
 14  sex_f      104 non-null    float64
 15  sex_m      104 non-null    float64
dtypes: float64(16)
memory usage: 13.1 KB

# Linear regression

In [20]:
x = df.drop('hdlngth', axis=1)

In [21]:
y = df['hdlngth']

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
linReg = LinearRegression()

In [26]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=63)

In [25]:
linReg.fit(x_train,y_train)

LinearRegression()

In [27]:
pred = linReg.predict(x_test)

In [28]:
r2=r2_score(y_test,pred)
mae=mean_absolute_error(y_test,pred)
mse=mean_squared_error(y_test,pred)
rmse=root_mean_squared_error(y_test,pred)

In [29]:
print(r2)
print(mae)
print(mse)
print(rmse)

0.6734851742322898
1.472632965426477
3.533895075808989
1.8798657068548776

# Decision Tree regressiya

In [30]:
from sklearn.tree import DecisionTreeRegressor
treeReg = DecisionTreeRegressor()

In [31]:
treeReg.fit(x_train,y_train)

DecisionTreeRegressor()

In [32]:
pred1 = treeReg.predict(x_test)

In [33]:
r2=r2_score(y_test,pred1)
mae=mean_absolute_error(y_test,pred1)
mse=mean_squared_error(y_test,pred1)
rmse=root_mean_squared_error(y_test,pred1)

In [34]:
print(r2)
print(mae)
print(mse)
print(rmse)

-0.004228855721392311
2.71923076923077
10.868846153846155
3.296793313789349