In [45]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
tree_clas = DecisionTreeClassifier()
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
labeling = LabelEncoder()

In [46]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\medical_insurance.csv")

In [47]:
df.head()

,age,gender,bmi,children,discount_eligibility,region,expenses,premium
0,19,female,27.9,0,yes,southwest,16884.92,168.8492
1,18,male,33.8,1,no,southeast,1725.55,17.2555
2,28,male,33.0,3,no,southeast,4449.46,44.4946
3,33,male,22.7,0,no,northwest,21984.47,439.6894
4,32,male,28.9,0,no,northwest,3866.86,77.3372

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   1338 non-null   int64
 1   gender                1338 non-null   object
 2   bmi                   1338 non-null   float64
 3   children              1338 non-null   int64
 4   discount_eligibility  1338 non-null   object
 5   region                1338 non-null   object
 6   expenses              1338 non-null   float64
 7   premium               1338 non-null   float64
dtypes: float64(3), int64(2), object(3)
memory usage: 83.8+ KB

# mid term og'zaki savollar

In [1]:
# Model Evaluation nima?

# Model evaluation — bu modelining natijalarini baholash, uning qanchalik to‘g‘ri va ishonchli ishlashini o‘lchash jarayonidir.

In [2]:
# Decision Tree qanday ishlaydi? Over/Underfittingni DT da qanday oldini olsak bo’ladi?

# Decision tree malumotlarni turli qismlarga bolib chiqadi, if-else korinishiga oxshash shart bilan davom ettiradi
# Over fitting ni max_depth parametri bilan oldini olinadi underfitting oldini koproq va aniq data bilan oldi olinadi

In [3]:
# Linear Modellar qanday ishlaydi?

# bu model input va output data orasida chiziqli bog'liqlik borligi asosida ishlaydi

In [5]:
# Logistic Regressionda qanday funksiyadan foydalanamiz?

# bu classification da ishlatiladi va sigmoid funksiydan foydalanalinadi (1 taqsim 1 + e daragada -z)

In [6]:
# Modelni stabilligini taminlash usullari xaqida gapiring?

# datani validation qilayotganda random_state parametri orqali stabillikni saqlanadi va datani scaling qilish va datani standartization orqali
saqlanadi

In [7]:
# Robust va Standart scalingni qanday o’xshashlik Tomoni bor va ular qanday ishlaydi?

# bular features ni scale qiladi va faqat numerik qiymatlar bilan ishlaydi. Standart scaling asosan 0 atrofiga olib keladi lekin datada outlier bolsa cheksiz boliadi

In [8]:
# Target va Frequency encoding xaqida gapirib bering

# target encoding bu mean encoding ham deyiladi va target qiymatga boglangan boladi frequency encoding esa datasetda osha data nechi martda takrorlansa shu miqdorni uni orniga yozib qoyadi

# python coding

In [ ]:
#1  Berilgan so’zni boshi va oxirdagi so’zlardan so’z tuzadigan funksiya yarating
def sozYasavchi(soz):
    return soz[0] + soz[-1]

In [10]:
#2  Berilgan listdagi sonlar o’rta arifmetigini topadigan funskiya yarating
def meanFind(num):
    return sum(num)/len(num)

In [12]:
#3  Berilgan so’zni uzunligini topadigan funksiya yarating
def sozUzunligi(soz):
    return len(soz)

In [22]:
#4  Berilgan listdagi so’zlar ichidan eng uzunini toping
def sozUzun(soz):
    raqam = 0
    uzunSoz = ''
    for word in soz:
        if len(word) > raqam:
            raqam = len(word)
            uzunSoz = word
    return uzunSoz

In [27]:
sozUzun(['qwqw','qwqwqwqwq','eewewewewewwewewew','112'])

'eewewewewewwewewew'

In [32]:
#5  Berilgan listdagi eng katta, eng kichik sonlarni topadigan funksiya yarating
def minmax(num):
    kichik = min(num)
    katta = max(num)
    return 'kattasi ' ,katta, 'kichik ' ,kichik

In [33]:
minmax([1,2,3,4,5,6,7,899,1])

('kattasi ', 899, 'kichik ', 1)

In [35]:
#6   Funskiyaga berilgan faqat juft sonlarni kopaytmasini toping
def juftSon(nums):
    kopaytma = 1
    for num in nums:
        if num % 2 == 0:
            kopaytma *= num
    return kopaytma

In [36]:
juftSon([1,2,3,4,5,6,7])

48

In [37]:
#7 Funskiyaga berilgan faqat toq sonlarni kopaytmasini toping
def toqSon(nums):
    kopaytma = 1
    for num in nums:
        if num % 2 != 0:
            kopaytma *= num
    return kopaytma

In [38]:
toqSon([1,2,3,4,5,6])

15

# Machine Learning

In [39]:
#1 Funksiya yordamida missing qiymatlarni toldiring
def toldiruchi(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [40]:
#2 Funksiya yordamida encoding qiling
def encodlovchi(df):
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col, dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=labeling.fit_transform(df[col])
    return df

In [41]:
#3  Funksiya yordamida scaling  qiling
def scale_qil(df):
    num_col=df.select_dtypes(include=['int64','int32','float64']).columns.drop('Target qiymat')
    df[num_col]=minmax.fit_transform(df[num_col])
    return df

In [58]:
#4  Model training qiling(Linear regression)
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
tree_class, tree_Reg = DecisionTreeClassifier(), DecisionTreeRegressor()
lrModel = LinearRegression()
from sklearn.metrics import r2_score

df.head()

,age,bmi,children,expenses,premium,gender_female,gender_male,discount_eligibility_no,discount_eligibility_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.9,0,16884.92,168.8492,1,0,0,1,0,0,0,1
1,18,33.8,1,1725.55,17.2555,0,1,1,0,0,0,1,0
2,28,33.0,3,4449.46,44.4946,0,1,1,0,0,0,1,0
3,33,22.7,0,21984.47,439.6894,0,1,1,0,0,1,0,0
4,32,28.9,0,3866.86,77.3372,0,1,1,0,0,1,0,0

In [51]:
df = encodlovchi(df)

In [59]:
x = df.drop('expenses', axis=1)
y = df['expenses']

In [60]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=24)

# Linear regressiya

In [61]:
lrModel.fit(x_train,y_train)

LinearRegression()

In [62]:
pred1 = lrModel.predict(x_test)
print(r2_score(y_test,pred1))

0.8502362754164438

# 5 Decision tree regressiya

In [64]:
tree_Reg.fit(x_train,y_train)

DecisionTreeRegressor()

In [66]:
pred2 = tree_Reg.predict(x_test)
print(r2_score(y_test,pred2))

0.99772295656538

# 6 decision tree classification

In [68]:
x = df.drop('children',axis=1)
y = df['children']

In [69]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=42)

In [71]:
tree_clas.fit(x_train,y_train)

DecisionTreeClassifier()

In [72]:
pred3 = tree_clas.predict(x_test)

In [73]:
from sklearn.metrics import classification_report

print(classification_report(y_test,pred3))

              precision    recall  f1-score   support

           0       0.68      0.66      0.67       175
           1       0.38      0.38      0.38       100
           2       0.32      0.33      0.33        72
           3       0.43      0.47      0.45        43
           4       0.22      0.33      0.27         6
           5       0.25      0.17      0.20         6

    accuracy                           0.50       402
   macro avg       0.38      0.39      0.38       402
weighted avg       0.50      0.50      0.50       402