In [2]:
import pandas as pd
from sklearn.metrics import classification_report,confusion_matrix

In [2]:
y_actual = [1,0,1,0,1,0,0,1,1,0,1]
y_pred = [1,1,0,0,0,1,0,1,1,0,0]

In [3]:
c_m = confusion_matrix(y_actual,y_pred)

In [4]:
c_m

array([[3, 2],
       [3, 3]])

In [5]:
clas_report = classification_report(y_actual,y_pred)

In [6]:
print(clas_report)

              precision    recall  f1-score   support

           0       0.50      0.60      0.55         5
           1       0.60      0.50      0.55         6

    accuracy                           0.55        11
   macro avg       0.55      0.55      0.55        11
weighted avg       0.55      0.55      0.55        11

In [3]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\medical_insurance.csv")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   1338 non-null   int64
 1   gender                1338 non-null   object
 2   bmi                   1338 non-null   float64
 3   children              1338 non-null   int64
 4   discount_eligibility  1338 non-null   object
 5   region                1338 non-null   object
 6   expenses              1338 non-null   float64
 7   premium               1338 non-null   float64
dtypes: float64(3), int64(2), object(3)
memory usage: 83.8+ KB

In [4]:
def tozalobchi(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [5]:
tozalobchi(df)

,age,gender,bmi,children,discount_eligibility,region,expenses,premium
0,19,female,27.9,0,yes,southwest,16884.92,168.8492
1,18,male,33.8,1,no,southeast,1725.55,17.2555
2,28,male,33.0,3,no,southeast,4449.46,44.4946
3,33,male,22.7,0,no,northwest,21984.47,439.6894
4,32,male,28.9,0,no,northwest,3866.86,77.3372
...,...,...,...,...,...,...,...,...
1333,50,male,31.0,3,no,northwest,10600.55,212.0110
1334,18,female,31.9,0,no,northeast,2205.98,22.0598
1335,18,female,36.9,0,no,southeast,1629.83,16.2983
1336,21,female,25.8,0,no,southwest,2007.95,20.0795
1337,61,female,29.1,0,yes,northwest,29141.36,1165.6544

In [14]:
len(df['gender'].unique())

2

In [33]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [17]:
def encodlovchi(df):
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique() <=6:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])
    return df

In [26]:
df = encodlovchi(df)

In [27]:
x = df.drop('expenses', axis=1)

In [28]:
y = df['expenses']

In [29]:
x_train,y_train, x_test, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [30]:
log_reg = LogisticRegression()

In [31]:
log_reg.fit(x_train,x_test)

c:\Users\bunyo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [32]:
y_pred = log_reg.predict(y_train)

In [ ]:
print(classification_report(y_test, y_pred))

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\kaggleDataSet\House Price Prediction Dataset.csv")

In [25]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [26]:
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [14]:
df.Location.unique()

array(['Downtown', 'Suburban', 'Urban', 'Rural'], dtype=object)

In [48]:
def encoding(data):
    for cols in data.columns:
        if data[cols].dtype == 'object':
            if data[cols].nunique() < 5:
                dum = pd.get_dummies(data[cols], prefix=cols, dtype=int)
                data = pd.concat([data.drop(columns=[cols]), dum], axis=1)
            else:
                data[cols] = labeller.fit_transform(data[cols])
    return data

In [ ]:
def encodlovchi(df):
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique() <=6:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
        else:
            df[col]=encoder.fit_transform(df[col])
    return df

In [ ]:
df['Bedrooms']

dtype('int64')

In [49]:
encoding(df)

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban,Condition_Excellent,Condition_Fair,Condition_Good,Condition_Poor,Garage_No,Garage_Yes
0,1,1360,5,4,3,1970,149919,1,0,0,0,1,0,0,0,1,0
1,2,4272,5,4,3,1958,424998,1,0,0,0,1,0,0,0,1,0
2,3,3592,2,2,3,1938,266746,1,0,0,0,0,0,1,0,1,0
3,4,966,4,2,2,1902,244020,0,0,1,0,0,1,0,0,0,1
4,5,4926,1,4,2,1975,636056,1,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,295620,0,0,1,0,0,0,0,1,1,0
1996,1997,3046,5,2,1,2019,580929,0,0,1,0,0,0,0,1,0,1
1997,1998,1062,5,1,2,1903,476925,0,1,0,0,0,0,0,1,1,0
1998,1999,4062,3,1,2,1936,161119,0,0,0,1,1,0,0,0,0,1
1999,2000,2989,5,1,3,1903,482525,0,0,1,0,0,1,0,0,1,0