# Used words for model

In [ ]:
# model	  ------   Avtomobilning aniq nomi yoki modeli.

# model_index	----------   Modelning indeks yoki kod raqami (ma’lumotlar bazasida identifikatsiya uchun).

# displacement	--------    Dvigatel hajmi (odatda litr yoki kub santimetrda, masalan 2.0L).

# cylinders	---------    Dvigateldagi silindrlar soni (4, 6, 8 va hokazo).

# gears	---------    Uzatmalar qutisidagi tezliklar soni (masalan, 5 pog‘onali).

# transmission	-------   Uzatmalar qutisi turi (manual — qo‘lda, automatic — avtomat).

# mpg	--------    “Miles per gallon” — yonilg‘i tejamkorligi (1 gallon yonilg‘ida necha mil yuradi).

# aspiration	--------   Havo kirish turi: tabiiy (NA — naturally aspirated) yoki majburiy (turbo/supercharger).

# lockup_torque_converter	drive	--------  Avtomatik transmissiyada “lock-up” funksiyali moment o‘zgartirgich mavjudligi.

# max_ethanol   ---------    Yonilg‘idagi maksimal etanol foizi (masalan, E10 — 10% etanol).

# recommended_fuel	--------   Ishlab chiqaruvchi tavsiya qilgan yonilg‘i turi (Regular, Premium va hokazo).

# intake_valves_per_cyl	--------    Har bir silindrga to‘g‘ri keladigan kirish (havo/yonilg‘i) klapanlari soni.

# exhaust_valves_per_cyl	--------   Har bir silindrga to‘g‘ri keladigan chiqish (gaz) klapanlari soni.

# fuel_injection   ---------    Yonilg‘i purkash tizimi turi (port injection, direct injection va boshqalar).

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\bunyo\Downloads\Telegram Desktop\cars2018.csv")

In [4]:
df.sample(6)

,model,model_index,displacement,cylinders,gears,transmission,mpg,aspiration,lockup_torque_converter,drive,max_ethanol,recommended_fuel,intake_valves_per_cyl,exhaust_valves_per_cyl,fuel_injection
498,Mini COOPER S CLUBMAN ALL4,71,2.0,4,6,Manual,24,Turbocharged/Supercharged,N,All Wheel Drive,10,Premium Unleaded Recommended,2,2,Direct ignition
548,BMW 330i xDrive Gran Turismo,326,2.0,4,8,Automatic,27,Turbocharged/Supercharged,Y,All Wheel Drive,10,Premium Unleaded Recommended,2,2,Direct ignition
393,BMW M550i xDrive,550,4.4,8,8,Automatic,19,Turbocharged/Supercharged,Y,All Wheel Drive,10,Premium Unleaded Recommended,2,2,Direct ignition
164,BMW M4 Convertible,482,3.0,6,6,Manual,20,Turbocharged/Supercharged,N,"2-Wheel Drive, Rear",10,Premium Unleaded Required,2,2,Direct ignition
989,LEXUS NX 300h AWD,26,2.5,4,6,CVT,31,Naturally Aspirated,N,All Wheel Drive,15,Regular Unleaded Recommended,2,2,Multipoint/sequential ignition
624,Jaguar XJL,353,5.0,8,8,Automatic,18,Turbocharged/Supercharged,Y,"2-Wheel Drive, Rear",15,Premium Unleaded Recommended,2,2,Direct ignition

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   model                    1144 non-null   object
 1   model_index              1144 non-null   int64
 2   displacement             1144 non-null   float64
 3   cylinders                1144 non-null   int64
 4   gears                    1144 non-null   int64
 5   transmission             1144 non-null   object
 6   mpg                      1144 non-null   int64
 7   aspiration               1144 non-null   object
 8   lockup_torque_converter  1144 non-null   object
 9   drive                    1144 non-null   object
 10  max_ethanol              1144 non-null   int64
 11  recommended_fuel         1144 non-null   object
 12  intake_valves_per_cyl    1144 non-null   int64
 13  exhaust_valves_per_cyl   1144 non-null   int64
 14  fuel_injection           1144 non-null   object
dtypes: float64(1), int64(7), object(7)
memory usage: 134.2+ KB

,model_index,displacement,cylinders,gears,mpg,max_ethanol,intake_valves_per_cyl,exhaust_valves_per_cyl
count,1144.000000,1144.000000,1144.000000,1144.000000,1144.000000,1144.000000,1144.000000,1144.000000
mean,201.277098,3.087238,5.563811,6.935315,23.195804,15.292832,1.925699,1.922203
std,212.970084,1.322116,1.827500,1.636529,5.586052,15.699689,0.262374,0.267969
min,1.000000,1.000000,3.000000,1.000000,11.000000,10.000000,1.000000,1.000000
25%,36.000000,2.000000,4.000000,6.000000,19.000000,10.000000,2.000000,2.000000
50%,108.000000,3.000000,6.000000,7.000000,23.000000,10.000000,2.000000,2.000000
75%,323.750000,3.600000,6.000000,8.000000,26.000000,15.000000,2.000000,2.000000
max,821.000000,8.000000,16.000000,10.000000,58.000000,85.000000,2.000000,2.000000