In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\appearances.csv")

In [4]:
df.sample(5)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
1345270,3838028_387626,3838028,387626,405,405,2022-10-16,Leon Bailey,GB1,0,0,0,0,66
996570,3302924_205550,3302924,205550,172,601,2020-02-08,Marco Ilaimaharitra,BE1,1,0,0,0,83
1136517,3427074_469787,3427074,469787,11282,141,2021-03-08,Berkan Kutlu,TR1,1,0,0,0,90
1663395,4484497_139396,4484497,139396,1075,294,2025-01-08,Bruma,POCP,0,0,0,0,90
1425818,4056156_58429,4056156,58429,14589,14589,2023-04-22,Vladimir Poluyakhtov,RU1,0,0,0,0,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           object
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    object
 6   player_name             object
 7   competition_id          object
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(9), object(4)
memory usage: 169.3+ MB

In [6]:
df.isnull().sum()

appearance_id             0
game_id                   0
player_id                 0
player_club_id            0
player_current_club_id    0
date                      0
player_name               6
competition_id            0
yellow_cards              0
red_cards                 0
goals                     0
assists                   0
minutes_played            0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
labeller = LabelEncoder()

In [10]:
def encodlovchi(df):
    for col in df.columns:
        if df[col].dtype == 'object':
            if df[col].nunique() <= 4:
                dumies = pd.get_dummies(df[col], prefix='yangi', dtype=int)
                df = pd.concat([df.drop(columns=[col]), dumies], axis=1)
            else:
                df[col] = labeller.fit_transform(df[col])
    return df

In [11]:
df = encodlovchi(df)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1706806 entries, 0 to 1706805
Data columns (total 13 columns):
 #   Column                  Dtype
---  ------                  -----
 0   appearance_id           int64
 1   game_id                 int64
 2   player_id               int64
 3   player_club_id          int64
 4   player_current_club_id  int64
 5   date                    int64
 6   player_name             int64
 7   competition_id          int64
 8   yellow_cards            int64
 9   red_cards               int64
 10  goals                   int64
 11  assists                 int64
 12  minutes_played          int64
dtypes: int64(13)
memory usage: 169.3 MB

In [14]:
df.head()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,55694,2231978,38004,853,235,0,2673,6,0,0,2,0,90
1,55741,2233748,79232,8841,2698,1,20519,13,0,0,0,0,90
2,55775,2234413,42792,6251,465,1,20949,13,0,0,0,0,45
3,55776,2234418,73333,1274,6646,1,23556,13,0,0,0,0,90
4,55777,2234421,122011,195,3008,1,15316,13,0,0,0,1,90

In [17]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

def scale_qiluchi(df):
    num_cols = df.select_dtypes(include=['int64','int32']).columns.drop('goals')
    df[num_cols] = minmax.fit_transform(df[num_cols])
    return df

In [18]:
df = scale_qiluchi(df)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,0.032631,0.008627,0.027515,0.007724,0.002140,0.000000,0.106320,0.142857,0.0,0.0,2,0.000000,0.605442
1,0.032658,0.009377,0.057371,0.080144,0.024469,0.000268,0.816157,0.309524,0.0,0.0,0,0.000000,0.605442
2,0.032678,0.009658,0.030982,0.056663,0.004225,0.000268,0.833260,0.309524,0.0,0.0,0,0.000000,0.299320
3,0.032679,0.009660,0.053099,0.011541,0.060261,0.000268,0.936956,0.309524,0.0,0.0,0,0.000000,0.605442
4,0.032679,0.009662,0.088351,0.001759,0.027279,0.000268,0.609204,0.309524,0.0,0.0,0,0.166667,0.605442
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1706801,0.999579,0.989370,0.587869,0.008921,0.008939,1.000000,0.027127,0.285714,0.0,0.0,0,0.000000,0.557823
1706802,0.999579,0.989370,0.594094,0.008921,0.008939,1.000000,0.516964,0.285714,0.5,0.0,0,0.000000,0.040816
1706803,0.999580,0.989370,0.669016,0.008921,0.008939,1.000000,0.539040,0.285714,0.0,0.0,1,0.000000,0.605442
1706804,0.999581,0.989370,0.671276,0.008921,0.008939,1.000000,0.747345,0.285714,0.0,0.0,0,0.000000,0.605442
1706805,0.999581,0.989370,0.067863,0.009429,0.009447,1.000000,0.042997,0.285714,0.0,0.0,0,0.000000,0.258503