In [1]:
import pandas as pd

In [2]:
y_actual = [3,4.5,5,5,5,4,4.5]
y_predict = [2.5,4,6,4.5,8,5,6.2]

In [59]:
from sklearn.metrics import r2_score, mean_absolute_error,mean_squared_error

In [9]:
r2 = r2_score(y_actual, y_predict)
mae = mean_absolute_error(y_actual,y_predict)
mse = mean_squared_error(y_actual,y_predict)
rmse = pow(mse,(1/2))

In [11]:
print(r2)
print(mae)
print(mse)
print(rmse)

-3.554666666666667
1.1714285714285713
2.0914285714285716
1.4461772268392874

In [41]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\Car Sell Dataset.csv")

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140904 entries, 0 to 140903
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Brand          140904 non-null  object
 1   Model Name     140904 non-null  object
 2   Model Variant  140904 non-null  object
 3   Car Type       140904 non-null  object
 4   Transmission   140904 non-null  object
 5   Fuel Type      140904 non-null  object
 6   Year           140904 non-null  int64
 7   Kilometers     140904 non-null  int64
 8   Owner          140904 non-null  object
 9   State          140904 non-null  object
 10  Accidental     140904 non-null  object
 11  Price          140904 non-null  int64
dtypes: int64(3), object(9)
memory usage: 12.9+ MB

In [6]:
df.sample(10)

,Brand,Model Name,Model Variant,Car Type,Transmission,Fuel Type,Year,Kilometers,Owner,State,Accidental,Price
109663,Nissan,Micra,XE,Hatchback,Manual,Diesel,2014,113328,3rd+,West Bengal,Yes,235134
61006,Maruti Suzuki,Swift,Z,Sedan,Manual,Diesel,2021,95743,2nd,West Bengal,No,1008065
62164,Toyota,Glanza,V,Hatchback,Automatic,Diesel,2019,163073,1st,Punjab,No,548625
73065,Maruti Suzuki,Celerio,V,Hatchback,Manual,Petrol,2014,139422,3rd+,Kerala,Yes,328774
486,Honda,Brio,S,Hatchback,Automatic,Petrol,2014,73882,1st,Karnataka,No,1157970
137073,Maruti Suzuki,Celerio,Z,Hatchback,Manual,Diesel,2020,37776,1st,Chandigarh,No,1995000
56570,Maruti Suzuki,Ignis,V,Hatchback,Automatic,Diesel,2017,70700,1st,Maharashtra,No,294756
51421,Toyota,Fortuner,E,SUV,Manual,Diesel,2016,177179,1st,Tamil Nadu,No,363825
21015,Maruti Suzuki,Ertiga,L,MPV,Manual,Electric,2023,135395,2nd,Karnataka,No,919987
125021,Skoda,Rapid,Ambition,Sedan,Manual,CNG,2014,176698,3rd+,Maharashtra,No,583550

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [ ]:

# ishlamayapti bu code

# def encodlovchi(df):
#     for col in df.columns.tolist():
#         if df[col].dtype == 'object':
#             if df[col].nunique() <= 5:
#                 dumies = pd.get_dummies(df[col], prefix='col', dtype=int)
#                 df.drop(columns=col, inplace=True)
#                 df[dumies.columns] = dumies
#             else:
#                 df[col] = encoder.fit_transform(df[col].astype(str))

In [40]:
def encodlovchi2(df):
    for col in df.columns.tolist():
        if df[col].dtype=='object':
            if df[col].nunique() <=6:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [42]:
df = encodlovchi2(df)

In [44]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

In [45]:
def scale_qiluvchi(df):
    for col in df.columns:
        if df[col].dtype != 'object':
            df[col] = minmax.fit_transform(df[[col]])

In [46]:
num_cols = df.select_dtypes(include=['int64','float64']).columns.drop('Price')

In [47]:
num_cols

Index(['Brand', 'Model Name', 'Model Variant', 'Year', 'Kilometers', 'State',
       'Car Type_Hatchback', 'Car Type_Luxury', 'Car Type_MPV', 'Car Type_SUV',
       'Car Type_Sedan', 'Transmission_Automatic', 'Transmission_Manual',
       'Fuel Type_CNG', 'Fuel Type_Diesel', 'Fuel Type_Electric',
       'Fuel Type_Hybrid', 'Fuel Type_Petrol', 'Owner_1st', 'Owner_2nd',
       'Owner_3rd+', 'Accidental_No', 'Accidental_Yes'],
      dtype='object')

In [48]:
df[num_cols] = minmax.fit_transform(df[num_cols])

In [49]:
df.head()

,Brand,Model Name,Model Variant,Year,Kilometers,State,Price,Car Type_Hatchback,Car Type_Luxury,Car Type_MPV,...,Fuel Type_CNG,Fuel Type_Diesel,Fuel Type_Electric,Fuel Type_Hybrid,Fuel Type_Petrol,Owner_1st,Owner_2nd,Owner_3rd+,Accidental_No,Accidental_Yes
0,0.529412,0.734940,0.012346,0.739130,0.909740,0.807692,547253,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.823529,0.590361,0.666667,0.782609,0.184420,0.576923,512050,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
2,0.588235,0.048193,0.987654,0.086957,0.641713,0.846154,678923,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,0.294118,0.385542,0.395062,0.565217,0.058701,0.000000,522500,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.529412,0.963855,0.839506,0.478261,0.709367,0.076923,401182,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0

In [50]:
x = df.drop(columns='Price', axis=1)

In [51]:
y = df['Price']

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [54]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [55]:
lr.fit(x_train,y_train)

LinearRegression()

In [56]:
pred = lr.predict(x_test)

array([815830.24011449, 543721.60410256, 623284.09818094, ...,
       781781.23102212, 758620.6870629 , 859740.25700005])

In [60]:
r2 = r2_score(y_test, pred)
mae = mean_absolute_error(y_test,pred)
mse = mean_squared_error(y_test,pred)
rmse = pow(mse,(1/2))

In [61]:
print(r2)
print(mae)
print(mse)
print(rmse)

0.25923231598890184
310437.68612952786
145549792476.5801
381509.8851623377