In [74]:
import pandas as pd

from sklearn.model_selection import train_test_split,KFold,cross_val_score
from sklearn.preprocessing import LabelEncoder
labeller = LabelEncoder()

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

svc = SVC()
Log_Class = LogisticRegression()
RF_Class = RandomForestClassifier()
DT_Class = DecisionTreeClassifier()

from sklearn.metrics import classification_report

In [26]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\heart.csv")

In [3]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [27]:
def encodlovchi(df):
    for cols in df.columns:
        if df[cols].dtype == 'object':
            if df[cols].nunique() >= 4:
                dum = pd.get_dummies(df[cols], prefix='new', dtype=int)
                df = pd.concat([df.drop(columns=[cols]),dum], axis=1)
            else:
                df[cols] = labeller.fit_transform(df[cols])
    return df

In [30]:
df = encodlovchi(df)

In [31]:
df

,Age,Sex,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,new_ASY,new_ATA,new_NAP,new_TA
0,40,1,140,289,0,1,172,0,0.0,2,0,0,1,0,0
1,49,0,160,180,0,1,156,0,1.0,1,1,0,0,1,0
2,37,1,130,283,0,2,98,0,0.0,2,0,0,1,0,0
3,48,0,138,214,0,1,108,1,1.5,1,1,1,0,0,0
4,54,1,150,195,0,1,122,0,0.0,2,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,1,132,0,1.2,1,1,0,0,0,1
914,68,1,144,193,1,1,141,0,3.4,1,1,1,0,0,0
915,57,1,130,131,0,1,115,1,1.2,1,1,1,0,0,0
916,57,0,130,236,0,0,174,0,0.0,1,1,0,1,0,0
917,38,1,138,175,0,1,173,0,0.0,2,0,0,0,1,0

In [33]:
x = df.drop('HeartDisease',axis=1)
y = df['HeartDisease']

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=22)

# SVC

In [46]:
svc.fit(x_train,y_train)

SVC()

In [47]:
svc_pred = svc.predict(x_test)

In [48]:
print(classification_report(y_test,svc_pred))

              precision    recall  f1-score   support

           0       0.64      0.67      0.65        76
           1       0.76      0.73      0.75       108

    accuracy                           0.71       184
   macro avg       0.70      0.70      0.70       184
weighted avg       0.71      0.71      0.71       184

# Logistic Regression

In [49]:
Log_Class.fit(x_train,y_train)

c:\Users\bunyo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [50]:
Log_pred = Log_Class.predict(x_test)

In [51]:
print(classification_report(y_test,Log_pred))

              precision    recall  f1-score   support

           0       0.81      0.80      0.81        76
           1       0.86      0.87      0.87       108

    accuracy                           0.84       184
   macro avg       0.84      0.84      0.84       184
weighted avg       0.84      0.84      0.84       184

# Random forest regression

In [60]:
RF_Class.fit(x_train,y_train)

RandomForestClassifier()

In [61]:
RF_pred = RF_Class.predict(x_test)

In [62]:
print(classification_report(y_test,RF_pred))

              precision    recall  f1-score   support

           0       0.85      0.84      0.85        76
           1       0.89      0.90      0.89       108

    accuracy                           0.88       184
   macro avg       0.87      0.87      0.87       184
weighted avg       0.87      0.88      0.87       184

# Decision tree Classication

In [63]:
DT_Class.fit(x_train,y_train)

DecisionTreeClassifier()

In [64]:
DT_pred = DT_Class.predict(x_test)

In [65]:
print(classification_report(y_test,DT_pred))

              precision    recall  f1-score   support

           0       0.72      0.80      0.76        76
           1       0.85      0.78      0.81       108

    accuracy                           0.79       184
   macro avg       0.78      0.79      0.78       184
weighted avg       0.79      0.79      0.79       184

# KFold orqali topish (SVC)

In [71]:
from sklearn.model_selection import KFold,cross_val_score
import numpy as np

In [72]:
kf = KFold(n_splits=5, shuffle=True, random_state=33)
crossing = cross_val_score(svc, X=x, y=y, cv=kf, scoring='accuracy')

print(np.mean(crossing))

0.721103587550487

# KFold orqali (Logistic Regression)

In [75]:
crossing1 = cross_val_score(Log_Class, X=x,y=y, cv=kf, scoring='accuracy')

print(np.mean(crossing1))

0.8486101211689236

c:\Users\bunyo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\bunyo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\bunyo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\bunyo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\bunyo\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

# KFold with Random forest

In [77]:
crossing2 = cross_val_score(RF_Class, X=x, y=y, cv=kf, scoring='accuracy')
print(np.mean(crossing2))

0.867112140650986

# Decision Tree with KFold

In [78]:
crossing3 = cross_val_score(DT_Class,x, y, cv=kf, scoring='accuracy')
print(np.mean(crossing3))

0.791951770016631

# Tabulate

In [66]:
from tabulate import tabulate

In [82]:
result = [
    ['SVC', 0.71, 0.723],
    ['Logistic Regression', 0.84, 'Nan'],
    ['Random Forest', 0.88, 0.867],
    ['Decision Tree', 0.79, 0.791]
]
title = ['Model','Orginal Accuracy', 'Accuracy_with_Kfold']

natija = tabulate(result,headers=title,tablefmt='fancy_grid',floatfmt='.3f')

print(natija)

╒═════════════════════╤════════════════════╤═══════════════════════╕
│ Model               │   Orginal Accuracy │   Accuracy_with_Kfold │
╞═════════════════════╪════════════════════╪═══════════════════════╡
│ SVC                 │              0.710 │                 0.723 │
├─────────────────────┼────────────────────┼───────────────────────┤
│ Logistic Regression │              0.840 │               nan     │
├─────────────────────┼────────────────────┼───────────────────────┤
│ Random Forest       │              0.880 │                 0.867 │
├─────────────────────┼────────────────────┼───────────────────────┤
│ Decision Tree       │              0.790 │                 0.791 │
╘═════════════════════╧════════════════════╧═══════════════════════╛