In [6]:
import pandas as pd

from sklearn.model_selection import train_test_split,KFold,cross_val_score
from sklearn.preprocessing import LabelEncoder
labeller = LabelEncoder()

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor

Lin_Reg = LinearRegression()
Log_Class = LogisticRegression()
RF_Reg = RandomForestRegressor()
DT_Class = DecisionTreeClassifier()

from sklearn.metrics import classification_report

In [26]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\heart.csv")

In [3]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [27]:
def encodlovchi(df):
    for cols in df.columns:
        if df[cols].dtype == 'object':
            if df[cols].nunique() >= 4:
                dum = pd.get_dummies(df[cols], prefix='new', dtype=int)
                df = pd.concat([df.drop(columns=[cols]),dum], axis=1)
            else:
                df[cols] = labeller.fit_transform(df[cols])
    return df

In [28]:
encodlovchi(df)

,Age,Sex,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,new_ASY,new_ATA,new_NAP,new_TA
0,40,1,140,289,0,1,172,0,0.0,2,0,0,1,0,0
1,49,0,160,180,0,1,156,0,1.0,1,1,0,0,1,0
2,37,1,130,283,0,2,98,0,0.0,2,0,0,1,0,0
3,48,0,138,214,0,1,108,1,1.5,1,1,1,0,0,0
4,54,1,150,195,0,1,122,0,0.0,2,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,1,132,0,1.2,1,1,0,0,0,1
914,68,1,144,193,1,1,141,0,3.4,1,1,1,0,0,0
915,57,1,130,131,0,1,115,1,1.2,1,1,1,0,0,0
916,57,0,130,236,0,0,174,0,0.0,1,1,0,1,0,0
917,38,1,138,175,0,1,173,0,0.0,2,0,0,0,1,0